apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels.name }}
  labels:
    name: {{ .Values.labels.name }}
    version: {{ .Values.labels.version }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.labels.name }}
      version: {{ .Values.labels.version }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
    type: {{ .Values.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.name }}
        version: {{ .Values.labels.version }}
      {{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
{{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Values.service.containername }}
        securityContext:
{{ toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
        env:
        - name: {{ .Values.env.key }}
          value: {{ .Values.env.value }}
        - name: {{ .Values.env.key2 }}
          value: {{ .Values.env.value2 }}
        - name: {{ .Values.env.key3 }}
          value: {{ .Values.env.value3 }}
        - name: {{ .Values.env.key4 }}
          value: {{ .Values.env.value4 }}
        - name: {{ .Values.env.key5 }}
          value: {{ .Values.env.value5 }}                                    
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        {{- if .Values.probe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- end }}
        resources:
{{ toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | nindent 8 }}
      {{- end }}
