apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  redis.port: MzY3OQ==  
  redis.masterGroupName: bXltYXN0ZXI=  
  redis.authKey: c2VuZGVsLXBhc3N3b3Jk  
  redis.password: c2VkZW0=  
