apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    name: {{ .Values.labels.name }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.labels.name }} 
    version: {{ .Values.labels.version }}
