apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.pdb.name2 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Values.sv.key2 }}
      version: {{ .Values.sv.value2 }}