replicaCount: 2

image:
  repository: s6confidence/espresso-app
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "web-v1"

probe: 
  enable: false

labels:
  name: espresso-shop-web
  version: v1

secret: 
  name: redis-secret

env:
  key: ProductCatalogUrl
  value: http://espresso-shop-product-catalog-svc:8091
  key2: ReviewsUrl
  value2: http://espresso-shop-reviews-svc:8092
  key3:  MASTER_GROUP_NAME
  value3: mymaster 
  key4:  AUTH_KEY
  value4: sentinel-password
  key5:  REDIS_PASSWORD
  value5: sedem

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: espresso-shop-web
  create: true
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: espresso-shop-web
  type: NodePort
  port: 8090 
  targetPort: 80 
  containername: http

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
 limits:
  cpu: 100m
  memory: 128Mi
requests:
  cpu: 100m
  memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  name: cpu
  type: Utilization
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  
podDisruptionBudget: 1
#podDisruptionBudget:
  #minAvailable: 1
  #maxUnavailable: 1
  #name: prod-pdb

minReadySeconds: 5
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1   

nodeSelector: {}

tolerations: []

affinity: {}
