NAME: shop-products
LAST DEPLOYED: Fri Jan 26 20:13:25 2024
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: shop-product/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: espresso-shop-product-catalog-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
       version: v1
---
# Source: shop-product/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: espresso-shop-product-catalog
  labels: 
    version: v1
---
# Source: shop-product/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-product-catalog-svc  
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    version: v1
---
# Source: shop-product/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espresso-shop-product-catalog
  labels:
    version: v1
spec:
  selector:
    matchLabels:
      name: espresso-shop-product-catalog
      version: v1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: espresso-shop-product-catalog
        version: v1
    spec:
      serviceAccountName: espresso-shop-product-catalog
      securityContext:
        {}
      containers:
      - name: http
        securityContext:
            {}
        image: "s6confidence/espresso-app:product-catalog-v1"
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: danny
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_HOST
          value: 
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: shop-product/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: espresso-shop-product-catalog-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: espresso-shop-product-catalog
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

NOTES:
1. Get the application URL by running these commands:
  http://chart-example.local/
