replicaCount: 2

labels:
  name: espresso-shop-product-catalog
  version: v1

secret: 
  name: postgres

env:
  key: POSTGRES_USER
  value: postgres
  key2: POSTGRES_PASSWORD
  value2: danny
  key3: POSTGRES_DB
  value3: postgres  
  key4: POSTGRES_HOST
  values: postgres-postgresql-ha-postgresql
cm: 
  name: postgres-config
  
image:
  repository: s6confidence/espresso-app 
  pullPolicy: Always
  tag: "product-catalog-v1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: espresso-shop-product-catalog
  create: true
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: espresso-shop-product-catalog-svc
  type: ClusterIP
  port: 8091
  targetPort: 80
  containername: http
probe: 
  enable: false

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  name: cpu
  type: Utilization
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

podDisruptionBudget: 1
#podDisruptionBudget:
  #minAvailable: 1
  #maxUnavailable: 1
  #name: prod-pdb

minReadySeconds: 5
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

